language: go

go:
  - 1.x

sudo: false

git:
  depth: 10

branches:
  only:
    - hugo

install:
  - go get github.com/magefile/mage
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  - cd ${TRAVIS_BUILD_DIR}

script:
  - hugo

deploy:
  - provider: pages
    target_branch: master
    local_dir: public
    edge: true
    skip_cleanup: true
    github_token: ${GITHUB_TOKEN}
    on:
      repo: SoCraTes-FR/socrates-fr.github.io
      branch: hugo
